### ISSUE TITLE
Be able to create a whiskey review

### ISSUE THREAD

**Issue by Veggissss** [Unrated-Limited-Unlimited/ua-frontend#11]
As a whiskey connoisseur, I want to extrapolate my fine taste to other users by creating reviews for selected whiskeys.

**Comment by MikalDr** [comment]
DoD: Being able to create whiskey reviews on the frontend site, which is then sent to the backend and stored.

**Comment by MikalDr** [comment]
The menu is almost complete, need to connect to endpoint.

**Comment by MikalDr** [comment]
I have created Mock data, and set it up against the endpoints. I am closing this as I deem it complete
