### ISSUE TITLE
Standard theme + moving theme button

### ISSUE THREAD

**Issue by 591337** [Unrated-Limited-Unlimited/ua-frontend#35]
- [ ] Fix theme persistency (static build)
- [x] Move button to settings (as a list of some kind)
- [x] Standard theme

**Comment by MikalDr** [comment]
@591337 what do with static build?

**Comment by MikalDr** [comment]
@591337  unable to access " profile -> settings " in static build as there i can not login.

**Comment by 591337** [comment]
@MikalDr Made a new build mode for static with mock `npm run build:staticmsw`. It works, but there are some problems with the app. This is a [#24](https://github.com/Unrated-Limited-Unlimited/ua-frontend/issues/24) problem.

We might have to think about if you should have to be logged in to change the theme and how to deal with that. Have put it in [#36](https://github.com/Unrated-Limited-Unlimited/ua-frontend/issues/36)

You can mark this as done if you are happy.

**Comment by MikalDr** [comment]
I am content with how it is now, and will mark this issue as complete @591337 Regarding being logged out and changing themes, lets discuss that for next sprint, as we will focus more on design choices then.
