### ISSUE TITLE
Add paging to "whiskey" page

### ISSUE THREAD

**Issue by MikalDr** [Unrated-Limited-Unlimited/ua-frontend#43]
The endpoint has been updated in regards to paging on the backend.

On the frontend we need to add a option to change page, and load new whiskey.

DoD:
- A call to the backend getting whiskey.
- Buttons (either a "load more" or a "1,2,3,...,n" system for loading pages
- Should be adaptable in regards to screen size

Acceptance Criteria:
- A button that can be pressed to load more whiskeys to display

**Comment by MikalDr** [comment]
getWhiskey(sortType: SortType, paging: Paging): [Whiskey]

paging {page, size}

**Comment by MikalDr** [comment]
This is impemented on the "grid-display" branch as infinite scrolling

**Comment by MikalDr** [comment]
@Veggissss when trying to query whiskey using paging, we get null.

line 58 in WhiskeyFetcher seems to fail. Please help 😄 

`10:59:37.666 [default-nioEventLoopGroup-1-11] WARN  n.g.e.SimpleDataFetcherExceptionHandler - Exception while fetching data (/getWhiskeys) : null cannot be cast to non-null type kotlin.collections.Map<*, *>
java.lang.NullPointerException: null cannot be cast to non-null type kotlin.collections.Map<*, *>
    at com.ulu.fetchers.WhiskeyFetcher.getWhiskeys$lambda$5(WhiskeyFetcher.kt:58)
    at graphql.execution.ExecutionStrategy.invokeDataFetcher(ExecutionStrategy.java:311)
    at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:287)
    at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:213)
    at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:55)
    at graphql.execution.Execution.executeOperation(Execution.java:161)`

**Comment by Veggissss** [comment]
Woops, workin on it

**Comment by Veggissss** [comment]
Should be fixed now in the [latest commit](https://github.com/Unrated-Limited-Unlimited/ua-backend/commit/96bb806b872837c657c0a02d773e7b4c5a6bacb0).

The sorting input changed

**Comment by MikalDr** [comment]
@Veggissss we get data now :+1: seems to work

**Comment by MikalDr** [comment]
Tested with the running DB on the server. Seems to work. Closing as it is now complete
