### ISSUE TITLE
Theme loading issue

### ISSUE THREAD

**Issue by MikalDr** [Unrated-Limited-Unlimited/ua-frontend#45]
When refreshing the page, the theme changes.
This may be due to a fault in the "server.handle.ts"

Please look into the issue.

**Comment by MikalDr** [comment]
I believe this issue is solved on Grid-display

**Comment by 591337** [comment]
Might be fixed with #52 ??

**Comment by 591337** [comment]
We had a conversation, and decided to give up. No themes. It is more work than it is worth. :-) @MikalDr
