### ISSUE TITLE
check for not "200 OK" and "500 internal server error" upon login

### ISSUE THREAD

**Issue by h586613** [Unrated-Limited-Unlimited/ua-frontend#48]
add a check for anything not "200 OK" and then one for if it's "500 internal server error" upon login attempt to account

**Comment by h586613** [comment]
"As a user, i would like feedback if my login attempt was unsuccessful, so that i know to try again"

**Comment by 591337** [comment]
In addition,
- [ ] Check if the user is logged in when trying to give reviews, redirect to log in if not
- [ ] Register gets redirected to login page
- [ ] Logged-in user gets redirected to profile
- [ ] Non logged-in user gets error, why they were not logged in.
