### ISSUE TITLE
Browse and look at other users profiles

### ISSUE THREAD

**Issue by Veggissss** [Unrated-Limited-Unlimited/ua-frontend#6]
As a user, I want to be able to see other user profiles including my own. I want to be able to get to the profile by clicking at their review or searching for them.

**Comment by 591337** [comment]
Backend
- [ ] Search for users

Frontend
- [ ] Page for other profiles
- [ ] Get to the profile from a comment
- [ ] Search for a user

**Comment by 591337** [comment]
@Veggissss It would make my life easier if I could get the user by id instead of username. If not, then the username needs some limits to what characters you can use so that it can be put in the url

**Comment by 591337** [comment]
Rest of the frontend stuff is in #44
