### ISSUE TITLE
View a list of whiskeys

### ISSUE THREAD

**Issue by Veggissss** [Unrated-Limited-Unlimited/ua-frontend#7]
As a user, I want to view a list of whiskey products with details such as image, name and rating.

**Comment by MikalDr** [comment]
The website is created, hard to finish the fetch and such before the endpoints are up, or the mock endpoints are working.

**Comment by MikalDr** [comment]
DOD: A clean view showing a list of whiskeys. This should be modular, to be used for both search and recommendation
