### ISSUE TITLE
Look at other users reviews

### ISSUE THREAD

**Issue by Veggissss** [Unrated-Limited-Unlimited/ua-frontend#8]
As a user, I want to see reviews with rating along with comments for a selected whiskey.

- [ ] When looking at a whiskey, you can look at the reviews of other whiskeys

**Comment by MikalDr** [comment]
Made the components and such for the menu, all left is to connect to endpoint. Might need some help with this as I am not that competent with GraphQL

**Comment by MikalDr** [comment]
When entering a whiskey page, you are able to look at other review on that specific whiskey. This is mocked, and connected to endpoints.
Closing this issue.
